                 
function [optsNum,optsPhys] = Test_CahnHillardBox_Vel()

    %Numerical Parameters    
    Phys_Area = struct('y1Min',0,'y1Max',10,'N1',22,...
                       'y2Min',-10,'y2Max',10,'L2',4,'N2',22);
    
    Plot_Area = struct('y1Min',0,'y1Max',10,'N1',100,...
                       'y2Min',-10,'y2Max',10,'L2',3,'N2',100);
    
    %Sub_Area  = Phys_Area;
    Sub_Area = struct('y1Min',5,'y1Max',10,'N1',20,...
                      'y2Min',0,'y2Max',5,'N2',20);    
        
    optsNum = struct('PhysArea',Phys_Area,...
                     'PlotArea',Plot_Area,'SubArea',Sub_Area,...
                     'DDFTCode','CahnHilliard_Vel_Box',...
                     'plotTimes',0:0.2:20);                            
                      
    optsPhys = struct('V1DV1','Vext_Cart_TestCahnHillard_1',...
                      'epsilon_w',0,'epsilon_w_end',0.0,...
                      'theta',pi/4,'Cn',0.6,...
                      'Ca',0.01,'Cak',0.6,'etaRho',1,'zetaRho',1,...
                      'kBT',0.7,...
                      'nParticles',100);
                 
    %Run File
    AddPaths();
    f = str2func(optsNum.DDFTCode);
    f(optsPhys,optsNum);                 

end                 

