function [optsNum,optsPhys] = DDFT_DiffusionBox_2Phase_Sat_1()
    
    Phys_Area = struct('shape','Box','N',[20,30],...
                       'y1Min',0,'y1Max',10,...
                       'y2Min',-10,'y2Max',10);
    
    Plot_Area = struct('N1',100,'N2',100,...
                       'y1Min',0,'y1Max',10,...
                       'y2Min',-10,'y2Max',10);
        
    Sub_Area = struct('shape','Box','N',[20,20],...
                      'y1Min',0,'y1Max',5,...
                      'y2Min',-10,'y2Max',10);    
                  
    FexNum = struct('Fex','Meanfield');%,'N',[20,20],'L',1);                                    
        
    optsNum = struct('PhysArea',Phys_Area,...
                     'PlotArea',Plot_Area,...
                     'SubArea',Sub_Area,...
                     'V2Num',FexNum,...
                     'plotTimes',0:0.2:6); 

    V1 = struct('V1DV1','Vext_Cart_5',...
                'V0',0.0,'epsilon_w',1,'y10',2,'y20',0,'tau',1,...
                'epsilon_w_end',0.0);

    V2 = struct('V2DV2','Phi2DLongRange','epsilon',1);

    optsPhys = struct('V1',V1,'V2',V2,...
                      'HSBulk','CarnahanStarling',...
                      'kBT',0.7,'Dmu',0);

	config = v2struct(optsPhys,optsNum);
    
    AddPaths();
    EX     = DDFT_2D(config);
    EX.Preprocess();
    EX.ComputeEquilibrium(EX.optsPhys.rhoLiq_sat);
    EX.IDC.doPlots(EX.GetRhoEq)
    
    EX.ComputeDynamics();    
end                 

