function DDFT_DiffusionWedgeInfinity_Case1()
    
    Phys_Area = struct('shape','InfWedge','N',[30,20],...
                       'R_in',1,'LR',2,...
                       'th1',-pi/3,'th2',pi*1/3);
    
    Plot_Area = struct('N',[80 80],...    %'shape','Box',
                      'y1Min',1,'y1Max',6,...
                      'y2Min',-pi/3,'y2Max',pi/3);
    
    
    Sub_Area = struct('shape','Wedge','N',[20,20],...
                      'y1Min',1,'y1Max',3,...
                      'y2Min',-pi*1/3,'y2Max',pi*1/3);
                  
    V2Num       = struct('Fex','Meanfield','N',[20,20],'L',1);                                        
        
    optsNum = struct('PhysArea',Phys_Area,...
                     'PlotArea',Plot_Area,...
                     'SubArea',Sub_Area,...                     
                     'V2Num',V2Num,...
                     'plotTimes',0:0.05:2);
                 
    V1       = struct('V1DV1','Vext_Cart_2','V0',0.1,'grav',-1,...
                       'a',[0.1,0.1],'b',[1 0],'y10',1,'y20',0);
                   
    V2       = struct('V2DV2','Gaussian','alpha',2,'epsilon',-0.06);                     
                      
    optsPhys = struct('V1',V1,'V2',V2,...
                     'kBT',0.7,...                     
                     'nParticlesS',50);
                 
    DDFTDynamics(optsPhys,optsNum);
                 
end