

DDFT_DiffusionBox_2Phase_1
DDFT_DiffusionBox_2Phase_2
DDFT_DiffusionBox_2Phase_3
DDFT_DiffusionBox_2Phase_Sat_1
DDFT_DiffusionBox_2Phase_Sat_2
DDFT_DiffusionHalfSpace_2Phase_Sat_1
DDFT_DiffusionHalfSpace_2Phase_Sat_2

Test_DDFT_DiffusionBox_MF;
Test_DDFT_DiffusionDisc_MF;

Test_DDFT_DiffusionHalfSpace_FMT
Test_DDFT_DiffusionHalfSpace_FMT_Triangle
Test_DDFT_DiffusionHalfSpace_MF

Test_DDFT_DiffusionInfCapillary_MF;
Test_DDFT_DiffusionInfDisc_MF;

Test_DDFT_DiffusionInfSpace_MF;

Test_DDFT_DiffusionInfSpace_FMT(false);
Test_DDFT_DiffusionInfSpace_FMT(true);

Test_DDFT_EqBox_2Phase_2
Test_DFT_EqInfCapillary_Slit

