function [optsNum,optsPhys] = DDFT_DiffusionBox_2Phase_Sat_2()

    %Numerical Parameters    
    Phys_Area = struct('y1Min',0,'y1Max',10,'N1',20,...
                       'y2Min',-10,'y2Max',10,'N2',40);
    
    Plot_Area = struct('y1Min',0,'y1Max',10,'N1',100,...
                       'y2Min',-10,'y2Max',10,'N2',100);
    
    %Sub_Area  = Phys_Area;
    Sub_Area = struct('y1Min',0,'y1Max',5,'N1',20,...
                      'y2Min',-10,'y2Max',10,'N2',20);    
        
    optsNum = struct('PhysArea',Phys_Area,...
                     'PlotArea',Plot_Area,'SubArea',Sub_Area,...
                     'plotTimes',0:0.5:75,...
                     'DDFTCode','DDFT_DiffusionBox_2Phase_Sat');                            
                      
    optsPhys = struct('V1DV1','Vext_Cart_Capillary_3',...
                      'V0',0.0,'epsilon_w',1,'y10',10,'y20',0,'tau',1,...
                      'epsilon_w_end',0.0,...
                      'HSBulk','MuCarnahanStarling',...
                      'kBT',0.7,...
                      'V2DV2','Phi2DLongRange',...
                      'nParticles',40);

    %Run File
    AddPaths();
    if(nargout == 0)
        f = str2func(optsNum.DDFTCode);    
        f(optsPhys,optsNum);
    end
end                 

