function Test1_DFT_1DBox_2Phase()

    %Numerical Parameters    
    Phys_Area = struct('yMin',0,'yMax',10,'N',100);
    
    Plot_Area = struct('yMin',0,'yMax',10,'N',500);    
        
    optsNum = struct('PhysArea',Phys_Area,...
                     'PlotArea',Plot_Area,...
                     'DDFTCode','DFT_1DBox_2Phase',...
                     'plotTimes',0:5:500);                            
                      
    optsPhys = struct('V1DV1','Vext_Cart_Capillary_1D',...
                      'epsilon_w1',0.3,'epsilon_w2',0.4,'epsilon_w3',0.2,...
                      'epsilon_w2_end',0.1,'epsilon_w3_end',0.5,'tau',2,...
                      'HSBulk','CarnahanStarling',...
                      'kBT',0.7,'gamma',8,'Re',1,...
                      'V2DV2','Phi1DLongRange',...
                      'nParticlesPerArea',0.2);
                 
    %Run File
    AddPaths();
    f = str2func(optsNum.DDFTCode);
    f(optsPhys,optsNum);                 

end                 

