function [optsNum,optsPhys] = Test_DDFT_EqBoxInf_2Phase()

    %Numerical Parameters    
    Phys_Area = struct('y1Min',-inf,'y1Max',inf,'L1',10,'N1',23,...
                       'y2Min',-4,'y2Max',4,'N2',23);
    
    Plot_Area = struct('y1Min',-10,'y1Max',10,'L1',20,'N1',200,...
                       'y2Min',-4,'y2Max',4,'N2',50);
            
    optsNum = struct('PhysArea',Phys_Area,'PlotArea',Plot_Area,...
                     'DDFTCode','DDFT_EqBoxInf_2Phase','Cutoff',2,...
                     'Conv_N',50,...
                      'plotTimes',0:0.1:10);   
                      
    optsPhys = struct('V1DV1','Vext_Cart_Slit_Static',...                                            
                      'HSBulk','MuCarnahanStarling',...
                      'kBT',0.7,...
                      'V2DV2','Phi2DLongRange',...
                      'V2DV2_1D','Phi1DLongRange');                 
    %Run File
    AddPaths();
    f = str2func(optsNum.DDFTCode);
    f(optsPhys,optsNum);                 

end                 

