DDFT_DiffusionInfInterval;
DDFT_DiffusionHIInfInterval;

DDFT_InertiaInfInterval;
DDFT_InertiaHIInfInterval;

DDFT_DiffusionSphericalInfInterval;
DDFT_DiffusionHISphericalInfInterval;

DDFT_InertiaSphericalInfInterval;
DDFT_InertiaHISphericalInfInterval;

DDFT_DiffusionInterval;
DDFT_InertiaInterval;




