function [optsNum,optsPhys] = DDFT_HalfSpace_FMT_2Phase_Sat_2_ShortTest()

    %Numerical Parameters    
	Phys_Area = struct('N',[3,60],'L1',3,'L2',2,'y2wall',0.,...
                       'N2bound',16,'h',1,'L2_AD',2.);
    
    Plot_Area = struct('y1Min',-8,'y1Max',8,'N1',80,'N2',80,...
                       'y2Min',0.5,'y2Max',10);
    
    %Sub_Area  = Phys_Area;
    Sub_Area = struct('y1Min',-1,'y1Max',1,'N',[20,20],...
                      'y2Min',0,'y2Max',2);    
                  
	Conv      = struct('L',[],'L2',1.,'N',[50,50]);
    
    Fex_Num   = struct('Fex','FMTRosenfeld_3DFluid',...
                       'Ncircle',1,'N1disc',24,'N2disc',24);

        
    optsNum = struct('PhysArea',Phys_Area,...
                     'PlotArea',Plot_Area,'SubArea',Sub_Area,...
                     'plotTimes',0:0.1:6,...
                     'Conv',Conv,'FexNum',Fex_Num,...
                     'DDFTCode','DDFT_HalfSpace_FMT_2Phase_Sat');
                      

    V1 = struct('V1DV1','Vext_Cart_8',...
                      'V0',0.0,'y10',2,'y20',0,...
                      'epsilon_w',0.3,'tau',1,...
                      'epsilon_w_end',0.0,...
                      'L2',1.,...
                      'L1',4,'epsilon_w1',0.7,'w1_steepness',1);
                  
    V2 = struct('V2DV2','Phi2DLongRange','epsilon',1);	
    
    optsPhys = struct('V1',V1,'V2',V2,...                      
                      'kBT',0.6,...   
                      'Dmu',-0.0,'nSpecies',1,...
                      'sigmaS',1);

    %Run File
    if(nargout == 0)
        f = str2func(optsNum.DDFTCode);    
        f(optsPhys,optsNum);
    end
end                 

