Test_DDFT_DiffusionBox_MF;

Test_DDFT_DiffusionDisc_MF;

Test_DDFT_DiffusionInfDisc_MF;

Test_DDFT_DiffusionInfSpace_MF;

Test_DDFT_DiffusionInfSpace_FMT(false);
Test_DDFT_DiffusionInfSpace_FMT(true);