function z = GHR_lambda1(t)
        z = 1/(8*pi)*( 4*(2*t-pi).*sin(t) + ...
                       14*zeta(3) + 12*(cos(t)-1)) + ...
                       4*t.*(pi-t).*log((1-exp(1i*t))./(1+exp(1i*t))) +...                      
            +1/(2*pi)*(1i*(2*t-pi)*(polylog(2,exp(1i*t)) - polylog(2,-exp(1i*t)))...
                       -2*(polylog(3,exp(1i*t)) - polylog(3,-exp(1i*t)))...
                       +1i*(pi^3)/4);
        disp(['Max imaginary part: ',num2str(max(imag(z)))]);
        z = real(z); 
end