function [optsNum,optsPhys] = MeasureContactAngles_LDA()

    %Numerical Parameters    
    Phys_Area = struct('shape','HalfSpace_FMT','N',[1,40],...
                       'L1',4,'L2',5,'L2_AD',2.,...
                       'y2wall',0.,...
                       'N2bound',24,'h',1);
    
    Plot_Area = struct('y1Min',-10,'y1Max',10,'N1',100,'N2',100,...
                       'y2Min',0.5,'y2Max',10);
        
    Sub_Area = struct('shape','Box','y1Min',-1,'y1Max',1,'N',[20,20],...
                      'y2Min',0,'y2Max',2);
                                                        
	V2Num   = struct('Fex','SplitDisk','L',2,'L2',1.,'N',[40,40]);
        
    optsNum = struct('PhysArea',Phys_Area,...
                     'PlotArea',Plot_Area,'SubArea',Sub_Area,...
                     'plotTimes',0:0.1:6,...
                     'V2Num',V2Num);                                           

%     V1 = struct('V1DV1','Vext_Cart_5',...
%                       'V0',0.0,'y10',2,'y20',0,...
%                       'epsilon_w',1,'tau',1,...
%                       'epsilon_w_end',0.0,'wallAxis',2);
%     V2 = struct('V2DV2','Phi2DLongRange','epsilon',1);
    
    V1 = struct('V1DV1','Vext_BarkerHenderson_HardWall','epsilon_w',1);
    V2 = struct('V2DV2','BarkerHenderson_2D','epsilon',1,'LJsigma',1); 
    
                 
    optsPhys = struct('V1',V1,'V2',V2,...
                      'HSBulk','CarnahanStarling',...
                      'kBT',0.7,...                      
                      'Dmu',-0.05,...
                      'sigmaS',1);

    AddPaths();
    EX     = DDFT_2D(v2struct(optsPhys,optsNum));
    EX.Preprocess();
    EX.ComputeEquilibrium(EX.optsPhys.rhoGas_sat);                     
    EX.IDC.doPlots(EX.GetRhoEq());    
end                 

