function [optsNum,optsPhys] = Test_CahnHillardBox()

    %Numerical Parameters    
    Phys_Area = struct('y1Min',0,'y1Max',10,'N',[20,20],...
                       'y2Min',-10,'y2Max',10);
    
    Plot_Area = struct('y1Min',0,'y1Max',10,'N1',100,...
                       'y2Min',-7,'y2Max',7,'L2',3,'N2',100);
    
    %Sub_Area  = Phys_Area;
    Sub_Area = struct('y1Min',5,'y1Max',10,'N',[20,20],...
                      'y2Min',0,'y2Max',5);    
        
    optsNum = struct('PhysArea',Phys_Area,...
                     'PlotArea',Plot_Area,'SubArea',Sub_Area,...
                     'DDFTCode','CahnHilliard_Box',...
                     'plotTimes',0:0.1:1);                            
                      
    optsPhys = struct('V1DV1','Vext_Cart_TestCahnHillard_1',...
                      'epsilon_w',0,'epsilon_w_end',0.1,...
                      'theta',pi/4,'Cn',0.5,'Ca',1,...
                      'kBT',0.7,...
                      'nParticlesS',100);
                 
    %Run File
    if(nargout==0)
        AddPaths();
        f = str2func(optsNum.DDFTCode);
        f(optsPhys,optsNum);                 
    end

end                 

